image: Visual Studio 2015
environment:
  PATH: '%PATH%;C:\texlive\2016\bin\win32'
cache:
  - 'C:\texlive\2016\texmf-var\fonts\cache'
artifacts:
  - path: .\ango.pdf
    name: ango.pdf
init:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - git submodule update --init
  - choco install make
  - curl -O https://raw.githubusercontent.com/y-yu/install-tex-appveyor/master/install-tex.sh
  - bash ./install-tex.sh
  - tlmgr install collection-langjapanese collection-fontsrecommended
build_script:
  - make ango.pdf
