image: Visual Studio 2015
environment:
  PATH: '%PATH%;C:\texlive\2016\bin\win32;C:\Program Files\CMake\bin'
cache:
  - 'C:\texlive\2016\texmf-var\fonts\cache'
artifacts:
  - path: .\ango.pdf
    name: ango.pdf
install:
  - git submodule update --init
  - choco install cmake
  - curl -O https://raw.githubusercontent.com/y-yu/install-tex-appveyor/master/install-tex.sh
  - bash ./install-tex.sh
  - tlmgr install latexmk collection-langjapanese collection-fontsrecommended braket stmaryrd algorithms
build_script:
  - make ango.pdf
